/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordmanagerbeta;

import java.sql.*;
import br.com.passwordmanagerbeta.dba.ModuloConexao;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Helen
 */
public class FrmLogin extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void Logar(){
        String sql="select * from tbUsuarios where login=? and senha =?;";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txbUser.getText());
            String captura = new String(txbPass.getPassword());
            pst.setString(2, captura);
            rs = pst.executeQuery();
            if(rs.next()){
                String perfil=rs.getNString(5);
                String nameUser=rs.getString(2);
                
                
                //System.out.println(perfil);
                if(perfil.equals("admin")){
                    FrmPrincipal principal = new FrmPrincipal();
                    principal.setVisible(true);
                    FrmPrincipal.menReports.setEnabled(true);
                    FrmPrincipal.menSubUsers.setEnabled(true);
                    FrmPrincipal.menSubITDocs.setEnabled(true);
                    FrmPrincipal.menUserSET.setText(nameUser);
                    FrmPrincipal.menUserSET.setForeground(Color.red);                    
                    this.dispose();
                    conexao.close();
                }
                else {
                    FrmPrincipal principal = new FrmPrincipal();
                    principal.setVisible(true);
                    FrmPrincipal.menUserSET.setText(nameUser);
                    if(perfil.equals("suporte")){
                        FrmPrincipal.menUserSET.setForeground(Color.green);
                    }
                    else{
                        FrmPrincipal.menUserSET.setForeground(Color.blue);
                    }                    
                    this.dispose();
                    conexao.close();
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null, "usuário e/ou senha inválido(s)");
            }
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * Creates new form TelaLogin
     */
    public FrmLogin() {
        initComponents();
        
        conexao = ModuloConexao.conector();
        System.out.println(conexao);
        if(conexao != null){
            lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/passwordmanagerbeta/icons/icon-dba-online.png")));
        }
        else{
            lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/passwordmanagerbeta/icons/icon-dba-offline.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStatus = new javax.swing.JLabel();
        lbIconeUnico = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        txbUser = new javax.swing.JTextField();
        txbPass = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Manager Beta ( Full Platarform)");
        setResizable(false);

        lbStatus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/passwordmanagerbeta/icons/icon-dba-offline.png"))); // NOI18N

        lbIconeUnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconeUnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/passwordmanagerbeta/icons/icon-unico-title-color-semfundo.jpg"))); // NOI18N

        lbUsername.setText("Username");

        lbPassword.setText("Password");

        txbUser.setText("admin");
        txbUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txbUserKeyPressed(evt);
            }
        });

        txbPass.setText("admin");
        txbPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txbPassKeyPressed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbIconeUnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txbUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntrar))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbIconeUnico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar)
                    .addComponent(lbStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        Logar();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txbUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbUserKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_txbUserKeyPressed

    private void txbPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbPassKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_txbPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lbIconeUnico;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField txbPass;
    private javax.swing.JTextField txbUser;
    // End of variables declaration//GEN-END:variables
}
